// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pdf.revision.servicios.datos;

#nullable disable

namespace pdf.revision.servicios.data.migrations
{
    [DbContext(typeof(DbContextPdf))]
    [Migration("20250714231306_Conexion y Configuracion Pdf")]
    partial class ConexionyConfiguracionPdf
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("pdf.revision.model.ArchivoPdf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int")
                        .HasColumnName("prioridad");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ruta");

                    b.Property<int>("TotalPaginas")
                        .HasColumnType("int")
                        .HasColumnName("total_paginas");

                    b.Property<DateTime?>("UltimaRevision")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ultima_revision");

                    b.HasKey("Id");

                    b.ToTable("archivo_pdf", (string)null);
                });

            modelBuilder.Entity("pdf.revision.model.ParteDocumental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArchivoPdfId")
                        .HasColumnType("int")
                        .HasColumnName("archivo_pdf_id");

                    b.Property<int>("PaginaFin")
                        .HasColumnType("int")
                        .HasColumnName("pagina_fin");

                    b.Property<int>("PaginaInicio")
                        .HasColumnType("int")
                        .HasColumnName("pagina_inicio");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int")
                        .HasColumnName("tipo_documento_id");

                    b.HasKey("Id");

                    b.HasIndex("ArchivoPdfId");

                    b.HasIndex("TipoDocumentoId");

                    b.ToTable("parte_documental", (string)null);
                });

            modelBuilder.Entity("pdf.revision.model.RevisionPdf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArchivoPdfId")
                        .HasColumnType("int")
                        .HasColumnName("archivo_pdf_id");

                    b.Property<DateTime?>("FechaFinRevision")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_fin_revision");

                    b.Property<DateTime>("FechaInicioRevision")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_inicio_revision");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("ArchivoPdfId");

                    b.ToTable("revision_pdf", (string)null);
                });

            modelBuilder.Entity("pdf.revision.model.TipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("tipo_documento", (string)null);
                });

            modelBuilder.Entity("pdf.revision.model.ParteDocumental", b =>
                {
                    b.HasOne("pdf.revision.model.ArchivoPdf", "Archivo")
                        .WithMany("Partes")
                        .HasForeignKey("ArchivoPdfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pdf.revision.model.TipoDocumento", "TipoDocumento")
                        .WithMany("Partes")
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Archivo");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("pdf.revision.model.RevisionPdf", b =>
                {
                    b.HasOne("pdf.revision.model.ArchivoPdf", "Archivo")
                        .WithMany("Revisiones")
                        .HasForeignKey("ArchivoPdfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Archivo");
                });

            modelBuilder.Entity("pdf.revision.model.ArchivoPdf", b =>
                {
                    b.Navigation("Partes");

                    b.Navigation("Revisiones");
                });

            modelBuilder.Entity("pdf.revision.model.TipoDocumento", b =>
                {
                    b.Navigation("Partes");
                });
#pragma warning restore 612, 618
        }
    }
}
