// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pdf.revision.servicios.datos;

#nullable disable

namespace pdf.revision.servicios.data.migrations
{
    [DbContext(typeof(DbContextPdf))]
    [Migration("20251229160431_FixesProduccion")]
    partial class FixesProduccion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("pdf.revision.model.ArchivoPdf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConteoLOcal")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RutaLocal")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("TotalPaginas")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimaRevision")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("archivo_pdf", (string)null);
                });

            modelBuilder.Entity("pdf.revision.model.ParteDocumental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArchivoPdfId")
                        .HasColumnType("int");

                    b.Property<int?>("IdAgrupamiento")
                        .HasColumnType("int");

                    b.Property<int>("PaginaFin")
                        .HasColumnType("int");

                    b.Property<int>("PaginaInicio")
                        .HasColumnType("int");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArchivoPdfId");

                    b.HasIndex("TipoDocumentoId");

                    b.ToTable("parte_documental", (string)null);
                });

            modelBuilder.Entity("pdf.revision.model.RevisionPdf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArchivoPdfId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFinRevision")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInicioRevision")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ArchivoPdfId");

                    b.ToTable("revision_pdf", (string)null);
                });

            modelBuilder.Entity("pdf.revision.model.TipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tecla")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.HasKey("Id");

                    b.ToTable("tipo_documento", (string)null);
                });

            modelBuilder.Entity("pdf.revision.model.dtos.DtoEstadistica", b =>
                {
                    b.Property<int>("ArchivoPdfId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFinRevision")
                        .HasColumnType("datetime(6)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("pdf.revision.model.dtos.DtoEstadisticasUsuario", b =>
                {
                    b.Property<int>("Conteo")
                        .HasColumnType("int");

                    b.Property<string>("Fecha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("pdf.revision.model.ParteDocumental", b =>
                {
                    b.HasOne("pdf.revision.model.ArchivoPdf", "Archivo")
                        .WithMany("Partes")
                        .HasForeignKey("ArchivoPdfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pdf.revision.model.TipoDocumento", "TipoDocumento")
                        .WithMany("Partes")
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Archivo");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("pdf.revision.model.RevisionPdf", b =>
                {
                    b.HasOne("pdf.revision.model.ArchivoPdf", "Archivo")
                        .WithMany("Revisiones")
                        .HasForeignKey("ArchivoPdfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Archivo");
                });

            modelBuilder.Entity("pdf.revision.model.ArchivoPdf", b =>
                {
                    b.Navigation("Partes");

                    b.Navigation("Revisiones");
                });

            modelBuilder.Entity("pdf.revision.model.TipoDocumento", b =>
                {
                    b.Navigation("Partes");
                });
#pragma warning restore 612, 618
        }
    }
}
